### ISSUE TITLE
"excercise" instead of "exercise"

### ISSUE THREAD

**Issue by HSyr** [sealbro/dotnet.garmin.connect#13]
public Task<GarminExcerciseSets> GetActivityExcerciseSets(long activityId)
return _context.GetAndDeserialize<GarminExcerciseSets>(exerciseSetsUrl);
/// Fetch activity excercise sets
Task<GarminExcerciseSets> GetActivityExcerciseSets(long activityId);
public record GarminExcerciseSets
public async Task GetActivityExcerciseSets_NotNull()
var garminExcerciseSets = await _garmin.GetActivityExcerciseSets(activityId);
Assert.NotNull(garminExcerciseSets);

**Comment by sealbro** [comment]
Thank you, I will correct this copy-paste in the next major version.

**Comment by sealbro** [comment]
Fixed in 0.3.0
