### ISSUE TITLE
PaymentRequired for Garmin API

### ISSUE THREAD

**Issue by HSyr** [sealbro/dotnet.garmin.connect#24]
I'm getting exceptions starting today:

`Request [GET: https://connect.garmin.com/proxy/activitylist-service/activities/search/activities?startDate=2022-12-10&endDate=2022-12-17&start=0&limit=20] return code 402 (PaymentRequired).`

and

`Request [GET: https://connect.garmin.com/proxy/userprofile-service/userprofile/user-settings] return code 402 (PaymentRequired).`

I also tried another Garmin account that had not used the Garmin API at all in the past with the same result.

Garmin seems to have changed its policy. Any idea how to resolve this?

**Comment by sealbro** [comment]
Hello @HSyr thanks, the fast issue
I think something changed with the cookies
try to find what changed, if you know will be glad to review the PR

**Comment by sealbro** [comment]
@HSyr I am found what changed 

Garmin added new bearer token auth with the method https://connect.garmin.com/modern/di-oauth/exchange
and changed URLs

I am preparing PR and new release

**Comment by HSyr** [comment]
Great! Looking forward for the release.

**Comment by sealbro** [comment]
Released https://www.nuget.org/packages/Unofficial.Garmin.Connect/

**Comment by HSyr** [comment]
This was a fast fix! Works great @ [ASync](https://async.somee.com/). Thanks a lot @sealbro !
