### ISSUE TITLE
Use Refresh Token

### ISSUE THREAD

**Issue by rdelagato** [sealbro/dotnet.garmin.connect#26]
Feature Request: Use refresh token contained in the bearer token class

I would like to use the refresh token that is contained within the bearer token class but don't know how to format the request / what parameters and headers should be supplied in order to get a new access token. Is it possible to add this functionality to the repository? Also, if I am given the necessary parameters, I can create the PR for you to approve so that this can be implemented. Thanks for your help!

**Comment by sealbro** [comment]
Hi @rdelagato! You can look at that https://github.com/sealbro/dotnet.garmin.connect/blob/main/Garmin.Connect/GarminConnectContext.cs#L173
here need to change and make OAuth token refresh call 

If you describe which problem you want to do or which method to call, I will try to make a more common solution
