### ISSUE TITLE
Return connectIQ data?

### ISSUE THREAD

**Issue by daytonbrown** [sealbro/dotnet.garmin.connect#31]
It appears that the connectIQ custom activity data isn't returned with the GetActivities method.  Specifically I'm talking about a connectIQ connected scale. Is this a future add or am I missing something.  Thanks.

**Comment by sealbro** [comment]
Hi @daytonbrown !
Could you describe or add json which data you want ?

**Comment by sealbro** [comment]
Hi, @daytonbrown  Could you add the method name and response JSON you want?

**Comment by sealbro** [comment]
You can open this issue after adding additional information
