### ISSUE TITLE
Worker Service, Docker, prompted for a password reset.

### ISSUE THREAD

**Issue by oodoloo** [sealbro/dotnet.garmin.connect#38]
Hi together,
I am using this package in a .net 7.0 worker service, which I host in a Docker container.
Unfortunately I had this problem again today with my service hosted in a Docker container. The container has been running error-free for 2 weeks, the data was retrieved from Garmin without any problems and today I was suddenly prompted again for a password reset.
Does anyone have another idea what the problem could be?
As already mentioned in another issue, there is no real refresh of the access token, a new login is always performed. Could it have something to do with that? I am also unsure if a refresh could be implemented at all.

I'm starting to get a bit confused.

Many greetings

**Comment by sealbro** [comment]
Hi @oodoloo 
How many times do you call requests per hour/day and could you create a sample with dockerfile of how you use the library?

I don't know how to call a refresh token now, but I know only expire time access_token = 1h, resfresh_token = 2h, and suggest in the web browser a refresh token happened with the use of WebSocket

**Comment by oodoloo** [comment]
Hi sealbro,
sorry to get back to you only now, but unfortunately I just ran out of time.
I retrieve the data in a variable cycle. After each retrieval I determine a random waiting time, between 10 and 30 minutes, until the next retrieval.
I had noticed before, if it is always an identical time period and it is too short, then I get the problem even earlier that the credentials are reset.
That is I retrieve the data so maximum 4-5 times per hour and about 30-35 times a day.
I had even added something about not retrieving any data at all between 1am and 6am, hoping that would improve it, but unfortunately it did not.
I don't know if that makes so much sense when I deploy the Docker file.
Also somehow don't think it could have anything to do with the fact that they host my application as a Docker container. In any case, I would be very surprised.
I'd say I'll provide the two main classes for now, maybe you can tell from that if there's a problem in usage or something.
I'll add them as attachments to this message.

WorkerExample is the class in which actually everything happens.
AccountExample encapsulates only the access data of a user for whom the data should be retrieved and one instance of the GarminConnectClient.

Actually, it's not really much code yet, but it just doesn't work to run cleanly for a long time.

[ExampleClasses.zip](https://github.com/sealbro/dotnet.garmin.connect/files/12752200/ExampleClasses.zip)

**Comment by sealbro** [comment]
Can't reproduce, I tried catch the same problem.
I got email with "reset password" only one time when was connected from new proxy.

As a recommendation you can decrease requests intensively or make for each account request from different IPs.

If anybody meets the same problem, we will try investigating it again.
