### ISSUE TITLE
GarminConnectContext Model changed (javascript required)

### ISSUE THREAD

**Issue by danmajgaard** [sealbro/dotnet.garmin.connect#43]
As of 2023-09-26

Exception in:
TModel ParseJson<TModel>(string html, string key)

"Garmin.Connect.Exceptions.GarminConnectUnexpectedException: 'Model changed. VIEWER_USERPREFERENCES not found!'"

html contains the string: To sign in to your Garmin account, please enable JavaScript in your web browser.

**Comment by sealbro** [comment]
Hi, @danmajgaard 

Garmin changed token exchange and loading static preferences
Need more time for research 

Thank you for the fast notify

**Comment by danmajgaard** [comment]
Thanks for the awesome work ;)

**Comment by HSyr** [comment]
As expected, setting the Chrome like user agent header to httpclient didn't help. But I had to try...

**Comment by danmajgaard** [comment]
Lets hope theres a better way than selenium :D

https://medium.com/@jaethedeveloper/workaround-enable-javascript-to-view-the-page-content-when-web-scraping-in-c-2b30b35f625b

**Comment by cmiles** [comment]
@sealbro Thank you for this project!!!

I don't know the details of this project's code so not completely sure but I thought this issue https://github.com/philosowaffle/peloton-to-garmin/issues/524 might be a useful/relevant link.

Basically looks like the [peloton-to-garmin](https://github.com/philosowaffle/peloton-to-garmin) project have identified and decided on trying to do a C# version of [garth](https://github.com/matin/garth/tree/main) as a way forward for the auth issues. They appear to be trying to work quickly on this so could soon be a good source of reference code or ideas.

**Comment by sealbro** [comment]
Thank guys for the examples and existing libraries

Now I am trying to use [garth](https://github.com/matin/garth/tree/main) way if it works I will add an additional library with Selenium too

**Comment by jorgegregorio** [comment]
I maged to login and fetch activities today. I can send you the code (verry messy for now) ts entirely bases on Peoton-Garmin project.

**Comment by danmajgaard** [comment]
Wow, that was fast. I dont need the code urgently. Have a great weekend!

**Comment by cmiles** [comment]
If it helps anyone I did a mashup of C# translated [garth](https://github.com/matin/garth) (with some critical reference help from  [peloton-to-garmin](https://github.com/philosowaffle/peloton-to-garmin)) and the Activity APIs/Context/Client from this repo that I did to support (temporarily probably) one of my projects - [PointlessWaymarks.GarminConnect](https://github.com/cmiles/PointlessWaymarksProject/tree/main/PointlessWaymarks.GarminConnect). I didn't need MFA so I didn't do code for that and I'm not taking advantage of the refresh tokens in this version but like @jorgegregorio I've been able to login and download activities successfully!

**Comment by sealbro** [comment]
Thanks, guys!
I really glad any help

I realized the first part of "garth" with OAuth1 but it is not stable and returns 500 sometimes.

If you get the work code we can test and merge it early

**Comment by jorgegregorio** [comment]
Hi,
As I said, my code is still very messy and needs some review, I will not have the tine this weekend, anyway, here is the gardth part of my code, and you may adapt it as you please. 

Keep the good work.

[garth.txt](https://github.com/sealbro/dotnet.garmin.connect/files/12837192/garth.txt)

**Comment by sealbro** [comment]
Thanks @jorgegregorio 
I checked Auth from [peloton-to-garmin](https://github.com/philosowaffle/peloton-to-garmin) and it works better than my port ;)

I am cleaning up additional dependencies like Flurl.Http  
I will send PR how it is ready

**Comment by philosowaffle** [comment]
[peloton-to-garmin](https://github.com/philosowaffle/peloton-to-garmin) maintainer here, just a heads up the basic auth flow seems to be stable for me and my users over the past week, however the MFA flow is still not working.

**Comment by philosowaffle** [comment]
Fix for MFA was embarrassingly simple, I was missing a few fields from the [CommonQueryParams dict](https://github.com/philosowaffle/peloton-to-garmin/pull/549/files).  Just started working as soon as I added those params.

**Comment by sealbro** [comment]
Thank you @philosowaffle !

Yesterday I released without MFA [0.5.0](https://github.com/sealbro/dotnet.garmin.connect/releases/tag/0.5.0)
MFA I will add a little later with some fixes and refactor

**Comment by HSyr** [comment]
Amazing work!

**Comment by danmajgaard** [comment]
Just integrated the changes, works great! - Thanks for the swift response and awesome work :)

**Comment by raumongi** [comment]
Thanks for all the fixes! Everything works like a charm now.
