### ISSUE TITLE
Access to Gear

### ISSUE THREAD

**Issue by HSyr** [sealbro/dotnet.garmin.connect#8]
Any plans to allow to get the list of the gears for the activity?

**Comment by HSyr** [comment]
I have implemented new GarminGear and GarminGearType records and GetGearTypes, GetUserGears and GetActivityGears methods. Also I added support for the "yyyy-MM-dd\\THH:mm:ss.f" format and ""null" value used by Gears at DateTimeConverter.
I will contribute it as soon as I can.

**Comment by HSyr** [comment]
Pull with gears created

**Comment by sealbro** [comment]
@HSyr Thanks for the contribution!

**Comment by HSyr** [comment]
You are welcome!
