### ISSUE TITLE
Connection Failure - Change User Agent for Garmin API Changes

### ISSUE THREAD

**Issue by cmiles** [sealbro/dotnet.garmin.connect#94]
As of this AM I am getting an exception "Auth appeared successful but returned OAuth1 token is null. oauth1Response: []" when trying to connect.

Based on https://github.com/cyberjunky/python-garminconnect/commit/7c8670fc281f90183c2dcc5137cad09eab593df3 and https://github.com/matin/garth/commit/960d8c0ac0b68672e9edc7b9738ba77d60fa806a I quickly tested this project with the StaticUserAgent.cs class updated to the value below and it seems to have fixed the issue:

public class StaticUserAgent : IUserAgent
{
    public string New => "GCM-iOS-5.7.2.1";
}

I haven't created a pull request in part because the change is so small but also because one of the referenced pull requests notes this change as temporary and I did not make any time to understand changes/implications and if there is a better path to fixing this...

Thanks for the great project!!

**Comment by sanadas** [comment]
Thank you for raising the issue.

I could fix this issue locally only in my side as follows:



        public class CustomUserAgent : IUserAgent
        {
            public string New => "GCM-iOS-5.7.2.1";
        }

...

                    var authParameters = new BasicAuthParameters(login, password, new CustomUserAgent());

                    _garminConnectClient = new GarminConnectClient(new GarminConnectContext(new HttpClient(), authParameters));

**Comment by sealbro** [comment]
Thanks, guys! 
For research and the detailed fix guide.
