### ISSUE TITLE
Keep .net 6 support?

### ISSUE THREAD

**Issue by Moskus** [sealbro/dotnet.garmin.connect#97]
Is it possible to keep the support for .NET 6?

**Comment by sealbro** [comment]
Hi, dotnet 6 is outdated and not supported.
But you can use the 0.6.3 version with these fixes: https://github.com/sealbro/dotnet.garmin.connect/issues/94#issuecomment-2525345861 because, in 0.7.0, there are no new features.

You will use the latest when you update your app to the dotnet version.

**Comment by Moskus** [comment]
Version 0.6.3 can't authenticate (but 0.7.0 can): `: 'Auth appeared successful but returned OAuth1 token is null. oauth1Response: []'
`

**Comment by sealbro** [comment]
Yes. You can change one line in your code and 0.6.3 will work like 0.7.0
It described in issue #92

**Comment by Moskus** [comment]
Aha, there it was. I missed it! Thanks! :)
(I'd love .net6 support).
